version: "3"
services:
  server:
    build: .
    command: go run /go/src/github.com/dm03514/analysis-methodology-simple-http/cmd/server/main.go
    volumes:
      - .:/go/src/github.com/dm03514/analysis-methodology-simple-http
    ports:
      - 8080:8080

  prom:
    image: prom/prometheus:v2.1.0
    volumes:
     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    # network_mode: host
    ports:
     - 9090:9090
    depends_on:
     - exporter

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./tests/bin/postgres:/docker-entrypoint-initdb.d

  exporter:
    image: prom/node-exporter:latest
    ports:
     - 9100:9100

  grafana:
    image: grafana/grafana
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
    volumes:
      - ./config/grafana_prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./config/dashboards/service.json:/var/lib/grafana/dashboards/service.json
      - ./config/dashboards.yml:/etc/grafana/provisioning/dashboards/all.yml
    ports:
     - 3000:3000
    depends_on:
      - prom
